name: CI for tilepy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Restore Cached BSP File
        id: cache-bsp
        uses: actions/cache@v3
        with:
          path: ~/.skyfield/
          key: bsp-${{ runner.os }}-de440s
          restore-keys: |
            bsp-${{ runner.os }}-

      - name: Ensure BSP File is Available
        run: |
          mkdir -p ~/.skyfield
          if [ ! -f ~/.skyfield/de440s.bsp ]; then
            echo "Downloading BSP file..."
            wget -q https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de440s.bsp -O ~/.skyfield/de440s.bsp
          else
            echo "BSP file found in cache!"
          fi

      - name: Run unit tests
        run: pytest tests/

      - name: Run notebook tests
        run: pytest --nbmake examples/launcher/Tiling_Observations_Nobs.ipynb    #First test with only one jupyter notebook
